DATA:
  IMG_SIZE: 224
  BATCH_SIZE: 32
  SAMPLER_MODE: weighted
MODEL:
  TYPE: vit_b_32
  NAME: vit_b_32_A
  VIT:
    NUM_CLASSES: 8
TRAIN:
  EPOCHS: 100
  WARMUP_EPOCHS: 5
  WEIGHT_DECAY: 1e-8
  BASE_LR: 1e-2
  WARMUP_LR: 2e-08
  MIN_LR: 1e-5
  LINEAR_SCALE: False
  ACCUMULATION_STEPS: 1 
  LR_SCHEDULER:
    NAME: 'cosine'
    DECAY_EPOCHS: 2
    DECAY_RATE: 0.2
    WARMUP_PREFIX: True
    GAMMA: 0.1
    MULTISTEPS: []
  OPTIMIZER:
    NAME: 'sgd'
    EPS: 1e-8
    BETAS: (0.9, 0.999)
    MOMENTUM: 0.9
AUG:
  COLOR_JITTER: 0.4
  AUTO_AUGMENT: 'rand-m9-mstd0.5-inc1'
  REPROB: 0.25
  REMODE: 'pixel'
  RECOUNT: 1
  MIXUP: 0.8
  CUTMIX: 1.0
  CUTMIX_MINMAX: None
  MIXUP_PROB: 1.0
  MIXUP_SWITCH_PROB: 0.5
  MIXUP_MODE: 'batch'    
TEST:
  CROP: True