DATA:
  DATASET: breakhis_feat
  IMG_SIZE: 224
  BATCH_SIZE: 1
  SAMPLER_MODE: weighted
  DATA_PATH: '/media/admingpu/Crucial X6/BH_final_dataset/extracted_l2_d8/all_class/40x'
  NUM_WORKERS: 0
  PIN_MEMORY: False
MODEL:
  checkpoints: '/media/admingpu/Crucial X6/PHD_CODE/Swin-Transformer/output/vit_b_16_exp/best_model.pth'
  TYPE: experimental_vit_b_16_v2
  NAME: experimental_vit_b_12img_v2_acc32_A
  VIT:
    NUM_CLASSES: 8
  LABEL_SMOOTHING: 0.0
TRAIN:
  EPOCHS: 100
  WARMUP_EPOCHS: 5
  WEIGHT_DECAY: 1e-8
  BASE_LR: 1e-2
  WARMUP_LR: 2e-08
  MIN_LR: 1e-5
  LINEAR_SCALE: False
  ACCUMULATION_STEPS: 32
  LR_SCHEDULER:
    NAME: 'cosine'
    DECAY_EPOCHS: 10
    DECAY_RATE: 0.9
    WARMUP_PREFIX: True
    GAMMA: 0.1
    MULTISTEPS: []
  OPTIMIZER:
    NAME: 'sgd'
    EPS: 1e-8
    BETAS: (0.9, 0.999)
    MOMENTUM: 0.9
AUG:
  COLOR_JITTER: 0.0
  AUTO_AUGMENT: None
  REPROB: 0.5
  REMODE: 'pixel'
  RECOUNT: 1
  MIXUP: 0.0
  CUTMIX: 0.0
  CUTMIX_MINMAX: None
  MIXUP_PROB: 1.0
  MIXUP_SWITCH_PROB: 0.5
  MIXUP_MODE: 'batch'    
  HFLIP_PROB: 0.5
  VFLIP_PROB: 0.5
TEST:
  CROP: True
TAG: 'fold_1_x40_l2_d8_imgv2'
